def create_final_dictionary(dicts_list: list)-> list:
    """
    Get multiple dicts generated by processes and covert to a list of dicts which can be stored in MongoDB
    """
    result = []
    while len(dicts_list):
        current_dic = dicts_list.pop()
        for key in current_dic.keys():
            temp_dic = {'word': key, 'docs': current_dic[key]}
            for dic in dicts_list:
                try:
                    temp_dic['docs'].update(dic[key])
                except KeyError:
                    continue
                else:
                    del dic[key]
            result.append(temp_dic)
    return result


'''for i in range(len(body_words)):
    word = body_words[i]
    self.words.add(word)
    
    # If word does not exists in dictionary, initiate one
    if word not in self.bodies_dictionary.keys():
        self.bodies_dictionary[word] = {}
    # If doc.id not exists in postings list, initiate one
    if str(doc.id) not in self.bodies_dictionary[word].keys():
        self.bodies_dictionary[word][str(doc.id)] = []
    
    self.bodies_dictionary[word][str(doc.id)].append(i)'''
